### ISSUE TITLE
Server panics when providing consumer labels

### ISSUE THREAD

**Issue by jbielick** [jbielick/faktory_worker_node#14]
node.js version: n/a

npm/yarn version: n/a

faktory-server version: 0.7.0 (docker image)

`facktory-worker` package version: 0.9.2

#### Code sample:

```
› DEBUG=faktory* bin/faktory-work --label one --label two --concurrency 1
  faktory-worker:manager creating connection pool with max 3 +0ms
  faktory-worker:manager creating pool resource +2ms
  faktory-worker:client Connecting to server +0ms
  faktory-worker:manager starting 1 worker(s) +3ms
  faktory-worker:client:socket connect +0ms
  faktory-worker:client Established connection +4ms
  faktory-worker:client Shaking hands +0ms
  faktory-worker:client:server HI {"v":2} +0ms
  faktory-worker:client HELLO {"hostname":"HAL9000.local","v":2,"labels":["one","two"],"pid":48629,"wid":"45309e28"} +3ms
  faktory-worker:client:server OK +2ms
  faktory-worker:client client='HELLO {"hostname":"HAL9000.local","v":2,"labels":["one","two"],"pid":48629,"wid":"45309e28"}', server={ text: 'OK' } +1ms
  faktory-worker:client Connected +2ms
  faktory-worker:client:heart BEAT +0ms
  faktory-worker:client BEAT {"wid":"45309e28"} +1ms
  faktory-worker:client:server OK +3ms
  faktory-worker:client client='BEAT {"wid":"45309e28"}', server={ text: 'OK' } +0ms
  faktory-worker:client FETCH +2ms
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x794424]

goroutine 35 [running]:
github.com/contribsys/faktory/manager.(*manager).Fetch(0xc4200119e0, 0xf7aa80, 0xc420160120, 0xc420174198, 0x8, 0xc420172060, 0x0, 0x0, 0x500000c4201741c7, 0x7, ...)
	/root/go/src/github.com/contribsys/faktory/manager/manager.go:196 +0x2d4
github.com/contribsys/faktory/server.fetch(0xc42017e0c0, 0xc42010e000, 0xc4201741c7, 0x5)
	/root/go/src/github.com/contribsys/faktory/server/commands.go:81 +0x14c
github.com/contribsys/faktory/server.(*Server).processLines(0xc42010e000, 0xc42017e0c0)
	/root/go/src/github.com/contribsys/faktory/server/server.go:299 +0x232
github.com/contribsys/faktory/server.(*Server).Run.func1(0xc42010e000, 0xf7c640, 0xc420166050)
	/root/go/src/github.com/contribsys/faktory/server/server.go:147 +0x5c
created by github.com/contribsys/faktory/server.(*Server).Run
	/root/go/src/github.com/contribsys/faktory/server/server.go:142 +0x247
  faktory-worker:client:socket close +141ms
  faktory-worker:client Connection closed unexpectedly +132ms

  Error: Connection closed
      at Client.onClose (/Users/josh/code/faktory-worker/lib/client.js:330:26)
      at Socket.emit (events.js:160:13)
      at TCP._handle.close [as _onclose] (net.js:559:12)

[1]  + exit 2     bin/server
  faktory-worker:manager destroying pool resource +2s
  faktory-worker:manager creating pool resource +0ms
  faktory-worker:client Connecting to server +2s
  faktory-worker:client:socket error: { Error: connect ECONNREFUSED 127.0.0.1:7419 at Object._errnoException (util.js:1003:13) at _exceptionWithHostPort (util.js:1024:20) at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1194:14) errno: 'ECONNREFUSED', code: 'ECONNREFUSED', syscall: 'connect', address: '127.0.0.1', port: 7419 } +2s
{ Error: connect ECONNREFUSED 127.0.0.1:7419
    at Object._errnoException (util.js:1003:13)
    at _exceptionWithHostPort (util.js:1024:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1194:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 7419 }

```

#### Expected Behavior:

Labels are added to the worker process and displayed in the UI

#### Actual Behavior:

The server panics during `fetch`

#### Steps to reproduce the behavior or a test case:

Start a server: `bin/server &`

Start a worker with labels: `bin/faktory-work --label one --label two --concurrency 1`

**Comment by mperham** [comment]
Is it possible you are sending a FETCH with no queue names?

**Comment by jbielick** [comment]
Ah. That's it. Queue names should be logging `client FETCH {here} +2ms`. Thanks, Mike.
