### ISSUE TITLE
Error when SIGINT is received

### ISSUE THREAD

**Issue by danielwestendorf** [jbielick/faktory_worker_node#16]
node.js version: 8..0

npm/yarn version: 1.7.0

faktory-server version: 0.0.7

`facktory-worker` package version: github master

I'm killing my worker every hour via SIGINT as a work around to another problem. This causes an un-handled promise rejection error pointing at `lib/manager.js:104:38`. When the kill is done within a shorter timeframe, say 10 seconds, there is no problem.

Is this as simple as wrapping the `beat` async call in a try/catch block?

```js
  try {
    const response = await this.pool.use(client => client.beat());
    switch (response) {
      case 'quiet':
        this.quiet();
        break;
      case 'terminate':
        this.stop();
        break;
      default:
        // noop
        break;
    }
  } catch(err) {
  this.stop();
  }
```

#### Expected Behavior:

```bash
2018-08-11T21:36:07.359Z pdf-bot-pro:worker Shutting down per shutdownTimer
2018-08-11T21:36:07.360Z faktory-manager wid=2f4eaadf Stopping
(node:1) UnhandledPromiseRejectionWarning: Error: pool is draining and cannot accept work
    at Pool.acquire (/usr/src/app/node_modules/generic-pool/lib/Pool.js:434:9)
    at Pool.use (/usr/src/app/node_modules/generic-pool/lib/Pool.js:464:17)
    at Manager.beat (/usr/src/app/node_modules/faktory-worker/lib/manager.js:104:38)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

#### Actual Behavior:
Graceful shutdown

```
  pdf-bot-pro:worker Shutting down per shutdownTimer +10s
2018-08-11T21:49:45.303Z faktory-manager wid=7d1a53a8 Stopping
```

#### Steps to reproduce the behavior or a test case:

```js

setTimeout(() => {
  process.kill(process.id, 'SIGINT')
}, 3600000)

faktory.work(...)

```

```js

setTimeout(() => {
  process.kill(process.id, 'SIGINT')
}, 3600000)

faktory.work(...)

```

**Comment by jbielick** [comment]
Thanks for the issue report and great detail.

As you have discovered these are likely harmless errors. There are a couple race conditions in which a connection might be used after the `stop` command is given. 

There's a better / more stable graceful shutdown process in `2.0`. Would you like to give that a try? There shouldn't be any breaking changes to your code.

Additionally, you have another option: sending a `SIGTSTP` (quiet signal) as soon as possible in advance of sending a `SIGINT`.

**Comment by jbielick** [comment]
`2.0.0` is published as `faktory-worker@next` on npm.
