### ISSUE TITLE
ERR Unknown worker

### ISSUE THREAD

**Issue by counterbeing** [jbielick/faktory_worker_node#21]
node.js version: node:8.12-alpine

npm/yarn version: yarn 1.10.1

faktory-server version: 0.9.0

`facktory-worker` package version: ^2.2.0

#### Code sample:

I think that the code isn't entirely applicable here, and would just be noise. It's a crawler that uses puppeteer to continuously crawl pages and take screenshots. 

It may be worth noting that this is all running in a dockerized environment, and that these containers are currently experiencing issues with hitting their memory limits because some pages are just heavy.

#### Expected Behavior:

To continue processing jobs.

#### Actual Behavior:
```
(node:10) UnhandledPromiseRejectionWarning: ReplyError: ERR Unknown worker 97d0ef88
    at parseError (/app/node_modules/faktory-worker/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/app/node_modules/faktory-worker/node_modules/redis-parser/lib/parser.js:302:14)
(node:10) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2400)
```

It throws this error repeatedly.

#### Steps to reproduce the behavior or a test case:

This error only occurs after hours or days of running. It may well be that my solution is to catch this error and kill the process so that it restarts, as it's so intermittent.

**Comment by mperham** [comment]
This happens if a worker process does not heartbeat often enough, every 15 seconds is recommended.  Worker processes that have not sent a heartbeat in the last minute are considered dead and removed from the worker set (which is the Busy tab in the UI).  I guess a bug is that Faktory should close all TCP connections for that dead worker so the connections must be re-established.

**Comment by counterbeing** [comment]
Would you like me to move this issue to the faktory repo and close it here?

**Comment by jbielick** [comment]
@counterbeing I'm a little curious why your workers did not heartbeat for more than 15 seconds. A possible cause would be that the event loop was blocked. In any event, would you be willing to add `DEBUG=faktory-worker:*` to your process' env and record the logs right up to the process? If that's too verbose, possibly just `DEBUG=faktory-worker:client:heart,faktory-worker:worker`?

This should output a log line to STDOUT whenever the process heartbeats and the amount of time since the last heartbeat. If more than 15s passes between heartbeats I would expect the event loop is blocked. The heartbeat is scheduled with `setInterval`. If there's anything wrong with the library in this case I'd be interested in looking into it.

**Comment by counterbeing** [comment]
@jbielick Just based on my intuition, I would bet it's from trying to squeeze as much work out of my infrastructure as possible. I'm running everything in containers on a Kontena grid. I'd bet some of my containers get held up occasionally when chromium is eating a bunch of memory/cpu.

 I'm happy to dive into it to do some debugging. I will try your suggested logging, but the issue is rather intermittent.

**Comment by counterbeing** [comment]
Debug is enabled. Now we wait :)

**Comment by mperham** [comment]
Yes, please open a Faktory issue. Once a worker dies, its TCP connections should all be  closed.

**Comment by counterbeing** [comment]
The issue is now open in the Faktory repo. I'm going to leave this open as I'm hoping to produce some debugging output for @jbielick soon.

**Comment by counterbeing** [comment]
Just caught one @jbielick 

```log
2018-11-05T17:59:28.070Z [1]: "Evaluating script in context of page..."
2018-11-05T17:59:28.985Z [1]: FOCUS: "29 Ads found on page"
2018-11-05T17:59:29.251Z [1]: 2018-11-05T17:59:29.251Z faktory-worker:worker ACK cde0a46c-3216-4a3d-b1f7-4317689a0a85
2018-11-05T17:59:29.300Z [1]: 2018-11-05T17:59:29.300Z faktory-worker:worker executing 649ecdc7-ae8d-4216-839e-c86b53ddd1a3
2018-11-05T17:59:29.305Z [1]: "[SCRAPE] http://www.latimes.com/about/la-privacypolicy-20180703-story.html"
2018-11-05T17:59:29.565Z [1]: "Navigating to http://www.latimes.com/about/la-privacypolicy-20180703-story.html in format desktop"
2018-11-05T17:59:29.922Z [1]: 2018-11-05T17:59:29.922Z faktory-worker:client:heart BEAT
2018-11-05T17:59:44.923Z [1]: 2018-11-05T17:59:44.923Z faktory-worker:client:heart BEAT
2018-11-05T17:59:50.179Z [1]: "Evaluating script in context of page..."
2018-11-05T18:00:05.622Z [1]: 2018-11-05T18:00:02.298Z faktory-worker:client:heart BEAT
2018-11-05T18:00:46.302Z [1]: 2018-11-05T18:00:46.302Z faktory-worker:client:heart BEAT
2018-11-05T18:00:46.651Z [1]: Caught a page crashed error.
2018-11-05T18:00:46.302Z [1]: 2018-11-05T18:00:46.302Z faktory-worker:client:heart BEAT
2018-11-05T18:00:46.651Z [1]: Caught a page crashed error.
2018-11-05T18:00:56.011Z [1]: Downloading latest rules.
2018-11-05T18:00:56.184Z [1]: Starting worker...
2018-11-05T18:00:56.184Z [1]: 2018-11-05T18:00:56.182Z faktory-worker:worker work concurrency=1
2018-11-05T18:00:56.234Z [1]: 2018-11-05T18:00:56.216Z faktory-worker:worker executing c181af4d-8888-4580-a2d7-e2604ede4a09
2018-11-05T18:00:56.271Z [1]: "[SCRAPE] http://www.latimes.com/about/la-about-us-storygallery.html"
2018-11-05T18:00:57.593Z [1]: "Navigating to http://www.latimes.com/about/la-about-us-storygallery.html in format desktop"
2018-11-05T18:01:11.229Z [1]: 2018-11-05T18:01:11.188Z faktory-worker:client:heart BEAT
2018-11-05T18:01:26.227Z [1]: 2018-11-05T18:01:26.210Z faktory-worker:client:heart BEAT
2018-11-05T18:01:27.587Z [1]: "Evaluating script in context of page..."
2018-11-05T18:01:41.717Z [1]: 2018-11-05T18:01:41.621Z faktory-worker:client:heart BEAT
2018-11-05T18:02:39.392Z [1]: 2018-11-05T18:02:38.151Z faktory-worker:client:heart BEAT
2018-11-05T18:02:59.780Z [1]: 2018-11-05T18:02:59.249Z faktory-worker:client:heart BEAT
2018-11-05T18:03:00.729Z [1]: (node:9) UnhandledPromiseRejectionWarning: ReplyError: ERR Unknown worker e36f756d
2018-11-05T18:03:00.730Z [1]:     at parseError (/app/node_modules/faktory-worker/node_modules/redis-parser/lib/parser.js:179:12)
2018-11-05T18:03:00.730Z [1]:     at parseType (/app/node_modules/faktory-worker/node_modules/redis-parser/lib/parser.js:302:14)
2018-11-05T18:03:00.730Z [1]: (node:9) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
2018-11-05T18:03:00.731Z [1]: (node:9) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
2018-11-05T18:03:00.891Z [1]: (node:9) UnhandledPromiseRejectionWarning: ReplyError: ERR Unknown worker e36f756d
2018-11-05T18:03:00.891Z [1]:     at parseError (/app/node_modules/faktory-worker/node_modules/redis-parser/lib/parser.js:179:12)
2018-11-05T18:03:00.891Z [1]:     at parseType (/app/node_modules/faktory-worker/node_modules/redis-parser/lib/parser.js:302:14)
2018-11-05T18:03:00.898Z [1]: (node:9) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
2018-11-05T18:03:01.070Z [1]: Error: Socket closed unexpectedly
2018-11-05T18:03:01.070Z [1]:     at Client.onClose (/app/node_modules/faktory-worker/lib/client.js:345:20)
2018-11-05T18:03:01.070Z [1]:     at emitOne (events.js:116:13)
2018-11-05T18:03:01.070Z [1]:     at Socket.emit (events.js:211:7)
2018-11-05T18:03:01.070Z [1]:     at TCP._handle.close [as _onclose] (net.js:561:12)
2018-11-05T18:03:01.167Z [1]: (node:9) UnhandledPromiseRejectionWarning: TypeError: this.onConnectReject is not a function
2018-11-05T18:03:01.167Z [1]:     at Client.onConnect (/app/node_modules/faktory-worker/lib/client.js:317:12)
2018-11-05T18:03:01.167Z [1]:     at <anonymous>
2018-11-05T18:03:01.167Z [1]:     at process._tickCallback (internal/process/next_tick.js:189:7)
2018-11-05T18:03:01.178Z [1]: (node:9) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
2018-11-05T18:03:09.931Z [1]: 2018-11-05T18:03:09.927Z faktory-worker:client:heart BEAT
2018-11-05T18:03:11.624Z [1]: (node:9) UnhandledPromiseRejectionWarning: ReplyError: ERR Unknown worker e36f756d
2018-11-05T18:03:11.625Z [1]:     at parseError (/app/node_modules/faktory-worker/node_modules/redis-parser/lib/parser.js:179:12)
2018-11-05T18:03:11.625Z [1]:     at parseType (/app/node_modules/faktory-worker/node_modules/redis-parser/lib/parser.js:302:14)
2018-11-05T18:03:11.650Z [1]: (node:9) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
2018-11-05T18:03:39.771Z [1]: 2018-11-05T18:03:39.066Z faktory-worker:client:heart BEAT
```

**Comment by jbielick** [comment]
Awesome! Thanks.

This is particularly interesting to me:

```
2018-11-05T18:01:27.587Z [1]: "Evaluating script in context of page..."
2018-11-05T18:01:41.717Z [1]: 2018-11-05T18:01:41.621Z faktory-worker:client:heart BEAT
2018-11-05T18:02:39.392Z [1]: 2018-11-05T18:02:38.151Z faktory-worker:client:heart BEAT
2018-11-05T18:02:59.780Z [1]: 2018-11-05T18:02:59.249Z faktory-worker:client:heart BEAT
```

Between the first of these heartbeats and the second, 57 seconds past. I wonder if the "evalScript" or whatever operation is being done in the headless browser is somewhat synchronous? The event loop seems to be blocked for that period. I've used this library to identify blocking in some apps: https://www.npmjs.com/package/blocked

I think if `faktory` terminates the tcp connection this will sort of self-heal because connections reconnect and the connection pool will have other available connections. You may still see an error about the connection being closed unexpectedly, though.

Please re-open if there's some action I can take here.
