### ISSUE TITLE
Question: how to deal with connection timeouts?

### ISSUE THREAD

**Issue by aledbf** [jbielick/faktory_worker_node#23]
node.js version: v11.0.0
npm/yarn version: 6.4.1
faktory-server version: 0.9.1

`facktory-worker` package version:

#### Code sample:
```js

Error: read ETIMEDOUT
  at TCP.onStreamRead (internal/stream_base_commons.js:111:27) errno: 'ETIMEDOUT', code: 'ETIMEDOUT', syscall: 'read'
Unhandled Rejection at: Promise Promise {
  <rejected> Error: Connection closed
      at Client.onClose (/app/node_modules/faktory-worker/lib/client.js:327:26)
      at Socket.emit (events.js:182:13)
      at Socket.EventEmitter.emit (domain.js:442:20)
      at TCP._handle.close (net.js:606:12)
```

This means I should check for errors? If this error happens there is no reconnection to faktory (never starts processing jobs)

**Comment by CaryLandholt** [comment]
I've started seeing something similar
Also using faktory 0.9.1 docker
```shell
Error: Socket closed unexpectedly
    at Client.onClose (/reporter/node_modules/faktory-worker/lib/client.js:346:20)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at TCP._handle.close (net.js:599:12)
(node:48) UnhandledPromiseRejectionWarning: TypeError: this.onConnectReject is not a function
    at Client.onConnect (/reporter/node_modules/faktory-worker/lib/client.js:318:12)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:48) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 12)
```

**Comment by jbielick** [comment]
@aledbf Were you able to connect at all (even one connection) to the faktory server? With just that error and stack trace all I can guess is that you don't have connectivity to the faktory server instance. Since this seems like a network issue (Timed out), can you provide _a lot_ more detail about your environment and how your network is setup between the client and server?

This library uses a connection pool to pool faktory TCP connections to the server. They are created on-demand and the pool is scaled up and down. A connection timing out is out of our control here and may be indicative of some network issues. In any event, once the connection times out it is automatically closed and that connection won't be used anymore (it will be removed by the connection pool). So if you still have connectivity to the server, a working connection from the pool will be used on the next attempt to communicate with the server. At worst, only one job would be unacknowledged and eventually retried when it times out.

Can you independently confirm connectivity to the server and explain some details about your network between the server and client?

**Comment by aledbf** [comment]
> Were you able to connect at all (even one connection) to the faktory server?

Yes, this just happens randomly.

> can you provide a lot more detail about your environment and how your network is setup between the client and server?

Sure. I am using this module in a Kubernetes cluster in AWS, running faktory 0.9.1. This happened 10 times in the last 4 days (from a total of ~3500 jobs).

> So if you still have connectivity to the server, a working connection from the pool will be used on the next attempt to communicate with the server.

If the timeout happens no jobs are processed after the error (that's why I opened this issue). Restarting the process starts processing Jobs again. I want to avoid the need to read the logs to find the timeout error.

**Comment by jbielick** [comment]
@aledbf 

Thanks for the info.

I overlooked setting keepalive on the TCP socket for this library. It's been enabled and a new version published @ `v.2.2.2` on npm. I suspect kube-proxy (?) or the faktory server itself was disconnecting due to inactivity. 

I consider the second part of this issue—not reconnecting and ceasing job processing—to be an outstanding issue and I'll start working on that as well.

**Comment by jbielick** [comment]
> I consider the second part of this issue—not reconnecting and ceasing job processing—to be an outstanding issue and I'll start working on that as well.

This should be resolved in v3.0.0

**Comment by ttilberg** [comment]
Hi @jbielick -- I have been coming across this issue a lot recently on a Windows worker. I just updated from 2.2.0 to 3.02, and am still seeing this issue.

Jobs process normally for a while, and then I hit the error described above which takes down the entire process. 

On the worker, I'm running Windows 10, Node 10.16, faktory-worker-node 3.02. I do _not_ see this same issue on my ubuntu workers. Do you have any further insight into this issue on this platform specifically? Is there something I can do in my code to be more defensive? I didn't want to open a new issue yet since all of the context is here.

Here is an example output log from my app: https://pastebin.com/3r9Sq3KT
It shows the process working for a while sending a variety of ACKs and FAILs, and then crashing.

Here is how I'm initiating the worker with a few small redactions. I'm not very great with Node, so I'm including this in case it shows something obviously incorrect.

```js
const faktory = require('faktory-worker');
const worker = require('./worker-__');
const colors = require('colors');

const concurrency = parseInt(process.argv[2]) || 4;

// Setup the worker server & register the faktory worker(s).
(async () => {
  faktory.register('Harvest::__::Scraper', async (zipCode, section, aspect, rim, url=null) => {
    if (url) {
      await worker.extractSingleProduct(zipCode, section, aspect, rim, url);
    } else {
      await worker.run(zipCode, section, aspect, rim);
    }
  });
  faktory.register('Harvest::__::Scraper::InCartPricing', async (zipCode, section, aspect, rim, listing) => {
    await worker.inCartPricing(zipCode, section, aspect, rim, listing);
  });

  // MIDDLEWARE
  faktory.use(async (ctx, next) => {
    const start = new Date(Date.now()).toISOString();
    try {
      console.log(`${start} ${ctx.job.jid} ${ctx.job.jobtype} Start ${ctx.job.args}`);
      await next();
      const end = new Date(Date.now()).toISOString();
      console.log(`${end} ${ctx.job.jid} ${ctx.job.jobtype} ACK ${ctx.job.args}`.green);
    } catch (e) {
      const errTime = new Date(Date.now()).toISOString();
      console.log(`${errTime} ${ctx.job.jid} ${ctx.job.jobtype} FAIL ${ctx.job.args}`.red);
      throw e;
    }
  });

  await faktory.work({
    queues: ['www.__.com'],
    concurrency : concurrency
  });
})()

```


Please let me know if you'd like me to create a separate issue or provide more information, or if there is something I should change on my side.

**Comment by jbielick** [comment]
Hey, @ttilberg 

Sorry to hear that. I'm taking a look. I've opened a new issue with your description (very helpful info—thanks) to track it as "open".

#30
