### ISSUE TITLE
Worker crash on socket close

### ISSUE THREAD

**Issue by alexmic** [jbielick/faktory_worker_node#70]
node.js version: 12.14.1
faktory-server version:  pro-1.4.0
`faktory-worker` package version: 3.3.6

#### Expected Behavior:

Worker disconnects should be handled and retried.

#### Actual Behavior:

Unhandled exception leading to the worker not receiving any jobs.

The stack trace:

```
at TCP.<anonymous> (net.js:664:12)
at Socket.EventEmitter.emit (domain.js:475:20)
at Socket.emit (events.js:223:5)
at Connection.onClose (/app/node_modules/faktory-worker/lib/connection.js:120:41)
Error: Connection closed
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
at async Worker.tick (/app/node_modules/faktory-worker/lib/worker.js:76:19)
at async Client.fetch (/app/node_modules/faktory-worker/lib/client.js:176:22)
at /app/node_modules/generic-pool/lib/Pool.js:475:16
at Pool.destroy (/app/node_modules/generic-pool/lib/Pool.js:546:10)
at Pool._destroy (/app/node_modules/generic-pool/lib/Pool.js:137:42)
at ConnectionFactory.destroy (/app/node_modules/faktory-worker/lib/connection-factory.js:54:23)
at Connection.close (/app/node_modules/faktory-worker/lib/connection.js:205:12)
at new Promise (<anonymous>)
at /app/node_modules/faktory-worker/lib/connection.js:206:50
at Socket.end (net.js:580:31)
at Socket.Writable.end (_stream_writable.js:617:10)
at Socket.writeAfterFIN [as write] (net.js:447:14)
Error: This socket has been ended by the other party
2020.08.03 17:54:59 LOG5[11]: Connection closed: 8736 byte(s) sent to TLS, 23781 byte(s) sent to socket
```

**Comment by jbielick** [comment]
Hi Alex, thanks for the report. 

Question: do you have an error handler (catch) on the promise returned from `.work()`?

Are you able to share the code that starts the worker?

**Comment by alexmic** [comment]
I've just added it -- it was just `worker.work()` before. When would an error bubble up to the work function?

**Comment by jbielick** [comment]
Just covering the bases. There's a try/catch around worker.js:76, so I'm trying to make sense of the stack trace for the unhandled rejection.

https://github.com/jbielick/faktory_worker_node/blob/99bab78446be27280dc316fa76c6af5d67d4516c/lib/worker.js#L75-L81

I know there are some similar rules around not listening to emitted "error" events, and one is emitted on 79 in the case that `fetch` or `handle` fails, so I haven't ruled that out yet, either.

**Comment by alexmic** [comment]
For what's worth, I can sort-of reproduce if I restart the `faktory` server while the worker is running. I do get an unhandled exception even with try-catch (or `catch()` on promise). Stack trace:

```
api-worker_1         | (node:269) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 7)
api-worker_1         | (node:269) UnhandledPromiseRejectionWarning: Error: Connection closed
api-worker_1         |     at Connection.onClose (/usr/src/api/node_modules/faktory-worker/lib/connection.js:120:45)
api-worker_1         |     at /usr/src/api/node_modules/dd-trace/packages/dd-trace/src/scope/base.js:54:19
api-worker_1         |     at Scope._activate (/usr/src/api/node_modules/dd-trace/packages/dd-trace/src/scope/async_hooks.js:51:14)
api-worker_1         |     at Scope.activate (/usr/src/api/node_modules/dd-trace/packages/dd-trace/src/scope/base.js:12:19)
api-worker_1         |     at Socket.bound (/usr/src/api/node_modules/dd-trace/packages/dd-trace/src/scope/base.js:53:20)
api-worker_1         |     at Socket.emit (events.js:310:20)
api-worker_1         |     at Socket.EventEmitter.emit (domain.js:482:12)
api-worker_1         |     at TCP.<anonymous> (net.js:672:12)
api-worker_1         | (node:269) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 8)
api-worker_1         | error during forced shutdown: Error: Connection closed
api-worker_1         |     at Connection.onClose (/usr/src/api/node_modules/faktory-worker/lib/connection.js:120:45)
api-worker_1         |     at /usr/src/api/node_modules/dd-trace/packages/dd-trace/src/scope/base.js:54:19
api-worker_1         |     at Scope._activate (/usr/src/api/node_modules/dd-trace/packages/dd-trace/src/scope/async_hooks.js:51:14)
api-worker_1         |     at Scope.activate (/usr/src/api/node_modules/dd-trace/packages/dd-trace/src/scope/base.js:12:19)
api-worker_1         |     at Socket.bound (/usr/src/api/node_modules/dd-trace/packages/dd-trace/src/scope/base.js:53:20)
api-worker_1         |     at Socket.emit (events.js:310:20)
api-worker_1         |     at Socket.EventEmitter.emit (domain.js:482:12)
api-worker_1         |     at TCP.<anonymous> (net.js:672:12)
api-worker_1         | (node:269) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 8)
```

**Comment by alexmic** [comment]
OK, so I can handle all top-level errors with this:

```
function exitOnError (err) {
  console.log("Faktory worker crashed, exiting", err);
  process.exit(1);
}

worker.work(opts)
.then((worker) => { worker.on("error", exitOnError) })
.catch(exitOnError);
```

You're right that emitting an `error` is treated as an unhandled exception. If the process exists with code 1 it will most likely be restarted by the supervising process instead of just hanging.

**Comment by jbielick** [comment]
@alexmic since there's no other way of notifying the user (you) of the error without the `emit('error'`, do you think this is a documentation issue, or should there be a different approach to catching those errors?

**Comment by alexmic** [comment]
If the connection was closed, shouldn't the worker attempt to re-connect?

**Comment by jbielick** [comment]
If needed, yes. There's a connection pool with many connections. Once a connection is disconnected, it is removed from the pool. The next operation would check out a healthy connection from the pool. You should be able to restart the faktory server and watch the workers reconnect. Use `DEBUG=faktory* node myworker.js` to see the debug log lines.

**Comment by alexmic** [comment]
Hmm, currently when I restart the server the worker crashes due to emitting the error we discussed above.

**Comment by jbielick** [comment]
:) Yeah, that makes sense given our conversation here. What about when you _are_ listening for `error` events? What is the behavior then?

**Comment by alexmic** [comment]
If I leave `process.exit(1)` out of the exception handler then this happens:

1. The first time faktory restarts:
```
rker_1         |   faktory-worker:connection client='FETCH default search', server=undefined +1ms
api-worker_1         |   faktory-worker:connection-pool -1 +4ms
api-worker_1         |   faktory-worker:connection-pool +1 +1ms
api-worker_1         |   faktory-worker:connection connecting +2ms
api-worker_1         | Faktory worker crashed, exiting ReplyError: ERR read unix @->/root/.faktory/db/redis.sock: use of closed network connection
api-worker_1         |     at parseError (/usr/src/api/node_modules/redis-parser/lib/parser.js:179:12)
api-worker_1         |     at parseType (/usr/src/api/node_modules/redis-parser/lib/parser.js:302:14)
api-worker_1         |   faktory-worker:connection close +4ms
api-worker_1         |   faktory-worker:connection close +4ms
api-worker_1         |   faktory-worker:connection close +1ms
api-worker_1         |   faktory-worker:connection close +0ms
api-worker_1         |   faktory-worker:connection close +1ms
api-worker_1         |   faktory-worker:connection close +1ms
api-worker_1         |   faktory-worker:connection close +0ms
api-worker_1         | Error: connect ECONNREFUSED 172.18.0.4:7419
api-worker_1         |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
api-worker_1         |   errno: 'ECONNREFUSED',
api-worker_1         |   code: 'ECONNREFUSED',
api-worker_1         |   syscall: 'connect',
api-worker_1         |   address: '172.18.0.4',
api-worker_1         |   port: 7419
api-worker_1         | }
i-worker_1         |   faktory-worker:connection-pool attempts=1 +16ms
api-worker_1         |   faktory-worker:connection close +5ms
api-worker_1         |   faktory-worker:connection-pool +1 +966ms
api-worker_1         |   faktory-worker:connection connecting +967ms
api-worker_1         |   faktory-worker:connection-pool +1 +8ms
api-worker_1         |   faktory-worker:connection connecting +7ms
api-worker_1         |   faktory-worker:connection-pool +1 +4ms
api-worker_1         |   faktory-worker:connection connecting +5ms
api-worker_1         |   faktory-worker:connection-pool +1 +2ms
api-worker_1         |   faktory-worker:connection connecting +2ms
api-worker_1         |   faktory-worker:connection-pool +1 +3ms
api-worker_1         |   faktory-worker:connection connecting +2ms
api-worker_1         |   faktory-worker:connection HI {"v":2} +1ms
api-worker_1         |   faktory-worker:client handshake +6s
api-worker_1         |   faktory-worker:connection SEND: HELLO {"hostname":"2127e3cc3291","v":2,"labels":["runtime:node","queue:default","queue:search"],"pid":36,"wid":"6395def4-77f0-4c9b-8759-ffaa656b86da"} +1ms
```
It seems like the worker attempts to reconnect and succeeds.

2. I then restart the faktory server again:
```
er_1         |   faktory-worker:connection-pool -1 +8ms
api-worker_1         | [ERROR] 10:28:18 Error: read ECONNRESET
api-worker_1         | Faktory worker crashed, exiting Error: Connection closed
api-worker_1         |     at Connection.onClose (/usr/src/api/node_modules/faktory-worker/lib/connection.js:120:41)
api-worker_1         |     at /usr/src/api/node_modules/dd-trace/packages/dd-trace/src/scope/base.js:54:19
api-worker_1         |     at Scope._activate (/usr/src/api/node_modules/dd-trace/packages/dd-trace/src/scope/async_hooks.js:51:14)
api-worker_1         |     at Scope.activate (/usr/src/api/node_modules/dd-trace/packages/dd-trace/src/scope/base.js:12:19)
api-worker_1         |     at Socket.bound (/usr/src/api/node_modules/dd-trace/packages/dd-trace/src/scope/base.js:53:20)
api-worker_1         |     at Socket.emit (events.js:310:20)
api-worker_1         |     at Socket.EventEmitter.emit (domain.js:482:12)
api-worker_1         |     at TCP.<anonymous> (net.js:672:12)
api-worker_1         |   faktory-worker:connection close +12ms
api-worker_1         |   faktory-worker:connection close +1ms
api-worker_1         |   faktory-worker:worker stop +56s
api-worker_1         |   faktory-worker:worker quiet +0ms
api-worker_1         |   faktory-worker:worker awaiting in progress +1ms
api-worker_1         |   faktory-worker:worker all clear +992ms
api-worker_1         |   faktory-worker:connection-pool -1 +1s
api-worker_1         |   faktory-worker:worker shutdown timeout exceeded +24s
```
This happens consistently. The first attempt to reconnect succeeds, subsequent attempts fail and leave the worker in a zombie state, not consuming any jobs.

**Comment by jbielick** [comment]
@alexmic The debug logs are very helpful. Thank you for sharing that.

I think I'm seeing (based on some tests locally inducing certain failures and these logs) a race condition in which an error is emitted on connection after the handler is removed (internally). I'll take a closer look and may have a patch that you could try to see if it resolves this.

**Comment by alexmic** [comment]
Perfect, thanks!

**Comment by jbielick** [comment]
`v3.3.8` is published with two fixes:

- Fixes an issue in which a connection may emit `error` _after_ error event listener is removed during connection teardown.
- Adds a default error handler to the faktory worker in the event one has not been added. This prevents the worker from encountering an unhandled error event on connection failures during FETCH and rendering the worker a zombie.

**Comment by alexmic** [comment]
Very nice thanks for the quick turnaround. Would you mind publishing this fix to the typescript version as well as I'm using that one - the 3.x series doesn't work with typescript still.

**Comment by alexmic** [comment]
Hey @jbielick any update on the typescript package?

**Comment by jbielick** [comment]
Could you give `4.0.0` a try? No major API changes, just migrated to TypeScript.

**Comment by jbielick** [comment]
It does

**Comment by alexmic** [comment]
Hey @jbielick, I've installed 4.0.0 but I'm seeing the same behaviour as before i.e on second restart the worker does not re-connect :-/

**Comment by jbielick** [comment]
I would give 4.2.0 a try if you're having this issue (now or in the future). Please reopen if it persists.
