### ISSUE TITLE
Does not work on Kubernetes with Istio service mesh

### ISSUE THREAD

**Issue by pbstriker38** [jbielick/faktory_worker_node#84]
node.js version: 12.16.2

yarn version: v1.22.10

faktory-server version: 1.4.2

`facktory-worker` package version: 4.0.1

#### Code sample:

```js
const faktory = require("faktory-worker");

faktory.register("TestJob", async (test) => {
  console.log("DO NOT BE ALARMED!!! THIS IS A TEST!!!");
});

function exitOnError (err) {
  console.log("Faktory worker crashed", err);
}

faktory.work(
  {
    host: "faktory-headless",
    password: "password",
    queues: ["node"]
  }
)
.then((worker) => { worker.on("error", exitOnError); })
.catch(exitOnError);
```

#### Expected Behavior:

Jobs are processed

#### Actual Behavior:

No jobs are processed

#### Steps to reproduce the behavior or a test case:

1. Install minikube
1. Install Istio service mesh
1. Install Faktory using [this](https://artifacthub.io/packages/helm/adwerx/faktory) helm chart
1. Create docker image with the above `worker.js` script
1. create deployment using that image
1. view the logs of the worker pod

```shell
2020-11-06T22:41:45.944Z faktory-worker use -
2020-11-06T22:41:45.946Z faktory-worker registered TestJob
2020-11-06T22:41:45.947Z faktory-worker registered Test
2020-11-06T22:41:45.949Z faktory-worker:worker work concurrency=20
2020-11-06T22:41:45.950Z faktory-worker:client:heart BEAT
2020-11-06T22:41:45.952Z faktory-worker:connection-pool +1
2020-11-06T22:41:45.953Z faktory-worker:connection connecting
Error: connect ECONNREFUSED 172.18.0.6:7419
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '172.18.0.6',
  port: 7419
}
...
... more of these connection errors until the Istio sidecar is ready
...
2020-11-06T22:41:47.979Z faktory-worker:connection-pool attempts=5
2020-11-06T22:41:47.979Z faktory-worker:connection close
2020-11-06T22:41:48.981Z faktory-worker:connection-pool +1
2020-11-06T22:41:48.981Z faktory-worker:connection connecting
Faktory worker crashed TimeoutError: ResourceRequest timed out
    at ResourceRequest._fireTimeout (/usr/src/app/node_modules/generic-pool/lib/ResourceRequest.js:62:17)
    at Timeout.bound (/usr/src/app/node_modules/generic-pool/lib/ResourceRequest.js:8:15)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7) {
  name: 'TimeoutError'
}
2020-11-06T22:41:54.987Z faktory-worker:connection HI {"v":2,"i":7514,"s":"6fcd18472fd92d52"}
2020-11-06T22:41:54.988Z faktory-worker:client handshake
2020-11-06T22:41:55.021Z faktory-worker:connection SEND: HELLO {"hostname":"worker-7c6fcc8c6-zx8jd","v":2,"labels":[],"pid":1,"wid":"c313f705","pwdhash":"1a754d8c77a02a00f4fa01fc7e6e3e89e87444823188f78ffccb18a565844551"}
2020-11-06T22:41:55.025Z faktory-worker:connection OK
2020-11-06T22:41:55.025Z faktory-worker:connection client='HELLO {"hostname":"worker-7c6fcc8c6-zx8jd","v":2,"labels":[],"pid":1,"wid":"c313f705","pwdhash":"1a754d8c77a02a00f4fa01fc7e6e3e89e87444823188f78ffccb18a565844551"}', server='OK'
2020-11-06T22:42:05.030Z faktory-worker:connection timeout
2020-11-06T22:42:07.958Z faktory-worker:connection-pool -1
2020-11-06T22:42:07.959Z faktory-worker:connection-pool +1
2020-11-06T22:42:07.959Z faktory-worker:connection connecting
2020-11-06T22:42:07.961Z faktory-worker:connection close
2020-11-06T22:42:13.930Z faktory-worker:connection HI {"v":2,"i":5430,"s":"52aea839aa553172"}
2020-11-06T22:42:13.930Z faktory-worker:client handshake
2020-11-06T22:42:13.947Z faktory-worker:connection SEND: HELLO {"hostname":"worker-7c6fcc8c6-zx8jd","v":2,"labels":[],"pid":1,"wid":"c313f705","pwdhash":"cd62b616d1090ae685b23bcea4c977a9dcfe5a25c8ff723f915f3deb988f30b2"}
2020-11-06T22:42:13.951Z faktory-worker:connection OK
2020-11-06T22:42:13.951Z faktory-worker:connection client='HELLO {"hostname":"worker-7c6fcc8c6-zx8jd","v":2,"labels":[],"pid":1,"wid":"c313f705","pwdhash":"cd62b616d1090ae685b23bcea4c977a9dcfe5a25c8ff723f915f3deb988f30b2"}', server='OK'
2020-11-06T22:42:23.956Z faktory-worker:connection timeout
2020-11-06T22:42:29.926Z faktory-worker:connection-pool -1
2020-11-06T22:42:29.926Z faktory-worker:connection-pool +1
2020-11-06T22:42:29.927Z faktory-worker:connection connecting
2020-11-06T22:42:29.928Z faktory-worker:connection close
2020-11-06T22:42:35.930Z faktory-worker:connection HI {"v":2,"i":6818,"s":"3166ee0545ecad70"}
2020-11-06T22:42:35.931Z faktory-worker:client handshake
2020-11-06T22:42:35.953Z faktory-worker:connection SEND: HELLO {"hostname":"worker-7c6fcc8c6-zx8jd","v":2,"labels":[],"pid":1,"wid":"c313f705","pwdhash":"55a76fb257dded5b03e03a951ffec691de1cefa673eaadc805c3343a858da1e4"}
2020-11-06T22:42:35.956Z faktory-worker:connection OK
2020-11-06T22:42:35.956Z faktory-worker:connection client='HELLO {"hostname":"worker-7c6fcc8c6-zx8jd","v":2,"labels":[],"pid":1,"wid":"c313f705","pwdhash":"55a76fb257dded5b03e03a951ffec691de1cefa673eaadc805c3343a858da1e4"}', server='OK'
2020-11-06T22:42:45.927Z faktory-worker:connection timeout

... Then these handshakes and timeouts just keep going and no jobs are processed
```

**Comment by jbielick** [comment]
Hi, @pbstriker38 . Is there anyway you can rule out Istio? It would be ideal to reduce the number of variables at play here. Since Istio is a service mesh, it's _very likely_ causing some connection issues here. Is there any information you can share about your Istio sidecar configuration? Is Istio also sidecarring the faktory server?

**Comment by jbielick** [comment]
Additionally, any istio ingress/egress logs would be helpful.

**Comment by pbstriker38** [comment]
@jbielick Sidecar is on Faktory server and node client. Everything works if I turn off sidecar injection on the node client. I can provide logs on Monday.

**Comment by pbstriker38** [comment]
Also, I forgot to mention that I also spun up a ruby client in the same environment with sidecar injection and it worked without issue.

**Comment by pbstriker38** [comment]
@jbielick Here are the logs

node worker istio-proxy
```shell
[2020-11-09T18:02:22.417Z] "- - -" 0 - "-" "-" 182 49 14978 - "-" "-" "-" "-" "172.18.0.16:7419" outbound|7419||faktory-headless.default.svc.cluster.local 172.18.0.6:59874 172.18.0.16:7419 172.18.0.6:59802 - -
[2020-11-09T18:02:42.363Z] "- - -" 0 - "-" "-" 182 50 17004 - "-" "-" "-" "-" "172.18.0.16:7419" outbound|7419||faktory-headless.default.svc.cluster.local 172.18.0.6:60114 172.18.0.16:7419 172.18.0.6:60052 - -
[2020-11-09T18:03:04.333Z] "- - -" 0 - "-" "-" 182 50 17006 - "-" "-" "-" "-" "172.18.0.16:7419" outbound|7419||faktory-headless.default.svc.cluster.local 172.18.0.6:60352 172.18.0.16:7419 172.18.0.6:60302 - -
```

faktory istio-proxy
```shell
[2020-11-09T18:02:23.418Z] "- - -" 0 - "-" "-" 182 49 13978 - "-" "-" "-" "-" "127.0.0.1:7419" inbound|7419|server|faktory-headless.default.svc.cluster.local 127.0.0.1:47360 172.18.0.16:7419 172.18.0.6:59874 - -
[2020-11-09T18:02:43.363Z] "- - -" 0 - "-" "-" 182 50 16004 - "-" "-" "-" "-" "127.0.0.1:7419" inbound|7419|server|faktory-headless.default.svc.cluster.local 127.0.0.1:47598 172.18.0.16:7419 172.18.0.6:60114 - -
[2020-11-09T18:03:05.334Z] "- - -" 0 - "-" "-" 182 50 16006 - "-" "-" "-" "-" "127.0.0.1:7419" inbound|7419|server|faktory-headless.default.svc.cluster.local 127.0.0.1:47838 172.18.0.16:7419 172.18.0.6:60352 - -
```

Parsing the logs using [engarde](https://github.com/nitishm/engarde) utility
node worker
```json
{
  "authority": "-",
  "bytes_received": "182",
  "bytes_sent": "50",
  "duration": "17006",
  "forwarded_for": "-",
  "method": "-",
  "protocol": "-",
  "request_id": "-",
  "response_flags": "-",
  "status_code": "0",
  "tcp_service_time": "-",
  "timestamp": "2020-11-09T18:03:04.333Z",
  "upstream_service": "172.18.0.16:7419",
  "upstream_cluster": "outbound|7419||faktory-headless.default.svc.cluster.local",
  "upstream_local": "172.18.0.6:60352",
  "downstream_local": "172.18.0.16:7419",
  "downstream_remote": "172.18.0.6:60302",
  "requested_server": "-",
  "route_name": "-",
  "upstream_failure_reason": "-",
  "user_agent": "-",
  "mixer_status": "-",
  "original_message": "[2020-11-09T18:03:04.333Z] \"- - -\" 0 - \"-\" \"-\" 182 50 17006 - \"-\" \"-\" \"-\" \"-\" \"172.18.0.16:7419\" outbound|7419||faktory-headless.default.svc.cluster.local 172.18.0.6:60352 172.18.0.16:7419 172.18.0.6:60302 - -"
}
```

faktory server
```json
{
  "authority": "-",
  "bytes_received": "182",
  "bytes_sent": "50",
  "duration": "16006",
  "forwarded_for": "-",
  "method": "-",
  "protocol": "-",
  "request_id": "-",
  "response_flags": "-",
  "status_code": "0",
  "tcp_service_time": "-",
  "timestamp": "2020-11-09T18:03:05.334Z",
  "upstream_service": "127.0.0.1:7419",
  "upstream_cluster": "inbound|7419|server|faktory-headless.default.svc.cluster.local",
  "upstream_local": "127.0.0.1:47838",
  "downstream_local": "172.18.0.16:7419",
  "downstream_remote": "172.18.0.6:60352",
  "requested_server": "-",
  "route_name": "-",
  "upstream_failure_reason": "-",
  "user_agent": "-",
  "mixer_status": "-",
  "original_message": "[2020-11-09T18:03:05.334Z] \"- - -\" 0 - \"-\" \"-\" 182 50 16006 - \"-\" \"-\" \"-\" \"-\" \"127.0.0.1:7419\" inbound|7419|server|faktory-headless.default.svc.cluster.local 127.0.0.1:47838 172.18.0.16:7419 172.18.0.6:60352 - -"
}
```

**Comment by jbielick** [comment]
The only thing I can surmise is that this is probably a Istio / Envoy configuration issue. There's really no other issues I've seen with the TCP communication in which it would refuse to connect or not work entirely.
